name: "Android Release"

on:
  workflow_dispatch:

# https://github.com/expo/expo-github-action#publish-on-any-push-to-main
jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Build packages
        run: yarn build:android --local
      - uses: WyriHaximus/github-action-get-previous-tag@v1
        id: currenttag
      - name: Rename AAB
        run: mv build-*.aab subadapp-${{ steps.currenttag.outputs.tag }}.aab
      - uses: softprops/action-gh-release@v1
        with:
          files: subadapp-${{ steps.currenttag.outputs.tag }}.aab
          tag_name: ${{ steps.currenttag.outputs.tag }}
