name: "Release"

on:
  workflow_dispatch:

# https://github.com/expo/expo-github-action#publish-on-any-push-to-main
jobs:
  build-android:
    name: Build Android and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: WyriHaximus/github-action-get-previous-tag@v1
        id: currenttag
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Build packages
        run: yarn build:android --local
      - name: Rename AAB
        run: mv build-*.aab subadapp-${{ steps.currenttag.outputs.tag }}.aab
      - uses: softprops/action-gh-release@v1
        with:
          files: subadapp-${{ steps.currenttag.outputs.tag }}.aab
          tag_name: ${{ steps.currenttag.outputs.tag }}

  #publish:
  #  name: Publish
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: actions/setup-node@v2
  #      with:
  #        node-version: "lts/*"
  #    - uses: expo/expo-github-action@v6
  #      with:
  #        expo-version: 4.x
  #        token: ${{ secrets.EXPO_TOKEN }}
  #    - name: Install dependencies
  #      run: yarn install
  #    - name: Publish the app
  #      run: expo publish
